language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn run build
deploy:
  provider: script
  script: yarn deploy
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    branch: master